add_remove_link_home_page = '//*[@id="content"]/ul/li[2]/a'
ab_testing_homepage="A/B Testing"
basicauthbtn="Basic Auth"
brknimg_homepage="Broken Images"
checkbox_homepage="Checkboxes"
secondchckbox="(//input[@type='checkbox'])[2]"
context_menu_homepage="Context Menu"
digest_auth_homepage="Digest Authentication"
disappearing_elements="Disappearing Elements"
drag_drop_homepae="Drag and Drop"
dropdown_homepage="Dropdown"
dynamic_content_homepage="Dynamic Content"
dynamic_controls_homepage="Dynamic Controls"
dynamic_loading_homepage="Dynamic Loading"
entry_add_homepage="Entry Ad"
exit_intent_homepage="Exit Intent"
context_title="h3"
dropdownid="//select[@id='dropdown']"